[theme]
primaryColor = "#4D5382"
backgroundColor = "#fdfdf8"
secondaryBackgroundColor = "#ecebe3"
textColor = "#3d3a2a"
linkColor = "#3d3a2a"
borderColor = "#d3d2ca"
showWidgetBorder = true
baseRadius = "0.75rem"
buttonRadius = "0.75rem" 
font = "Nunito:https://fonts.googleapis.com/css2?family=Nunito&display=swap"
headingFontWeights = [600, 500, 500, 500]  
headingFontSizes = ["3rem", "2rem"]
codeFont = "'Space Mono':https://fonts.googleapis.com/css2?family=Space+Mono&display=swap"
codeFontSize = ".75rem"
codeBackgroundColor = "#CACF85"
showSidebarBorder = true
chartCategoricalColors = ["#cacf85","#8cba80","#79a48e","#658e9c","#59718f","#4d5382","#4f4d73","#514663","#615771"]

[theme.sidebar]
backgroundColor = "#f0f0ec"
secondaryBackgroundColor = "#ecebe3"
headingFontSizes = ["1.6rem", "1.4rem", "1.2rem"]
dataframeHeaderBackgroundColor = "#e4e4e0"